services:
  backend:
    build: ./backend
    container_name: medicine_reminder_backend

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg://user_medicine_reminder:password_medicine_reminder@db:5432/medicine_reminder

    depends_on:
      - db

  db:
    image: postgres:17
    container_name: medicine_reminder_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: user_medicine_reminder
      POSTGRES_PASSWORD: password_medicine_reminder
      POSTGRES_DB: medicine_reminder

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: